version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    volumes:
      - redis_data:/data
    networks:
      - backend

  worker:
    build: .
    container_name: job_worker
    command: ["python", "worker.py"]
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend
      
volumes:
  redis_data:

networks:
  backend:
