services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_students
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: studentpass
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: