version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
    command: ["python", "worker.py"]
    depends_on:
      - redis
