services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_library_crud
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: library
    ports:
      - "5454:5432"
    volumes:
      - ./library_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./init.sql:/docker-entrypoint-initdb.d/2_init.sql

volumes:
  pgdata4:
